version: "3"
services:
  vendor-portal:
    image: devops1977/selenium
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - THREAD_COUNT=4
      - TEST_SUITE=vendor-portal.xml
    volumes:
      - C:/Users/Sachin/Docker/workspace/03-automation-framework/outout/vendor-portal:/home/selenium-docker/test-output

  flight-reservation:
    image: devops1977/selenium
    environment:
    - BROWSER=firefox
    - HUB_HOST=hub
    - THREAD_COUNT=4
    - TEST_SUITE=flight-reservation.xml
    volumes:
    - C:/Users/Sachin/Docker/workspace/03-automation-framework/outout/flight-reservation:/home/selenium-docker/test-output